version: "3.9"

services:

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=students_db
      - PGDATA=/var/lib/postgresql/db_data
    volumes:
      - ./db/db_data:/var/lib/postgresql/db_data
    restart: always

  minio:
    image: bitnami/minio:2024.7.26
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - ./minio1:/bitnami/minio/data

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_compose
    ports:
      - '2181:2181'
    expose:
      - '2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  brocker:
    image: bitnami/kafka:latest
    container_name: brocker
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  serv_r:
    container_name: serv_r
    build:
      context: ./services/serv_r
      dockerfile: Dockerfile
    ports:
      - "9904:9904"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cd_students
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS=kafka:9092
    depends_on:
      - db
      - zookeeper
      - brocker_kafka

  serv_s:
    container_name: serv_s
    build:
      context: ./services/serv_s
      dockerfile: Dockerfile
    ports:
      - "9904:9904"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cd_students
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS=kafka:9092
    depends_on:
      - db
      - minio
      - zookeeper
      - brocker_kafka


