
package ru.serv_r.soap_client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SoapService", targetNamespace = "http://service.serv_s.ru/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapService {


    /**
     * 
     * @param arg0
     * @return
     *     returns ru.serv_r.soap_client.Students
     */
    @WebMethod(operationName = "OneToCard")
    @WebResult(partName = "return")
    public Students oneToCard(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns ru.serv_r.soap_client.StudentsArray
     */
    @WebMethod(operationName = "All")
    @WebResult(partName = "return")
    public StudentsArray all();

}
